# Tabs
hard_tabs = false
tab_spaces = 2

# Line Width
max_width = 120
use_small_heuristics = "Max"
comment_width = 120
wrap_comments = true

# Commas
trailing_comma = "Never"
match_block_trailing_comma = true

# Single-Line Blocks
fn_single_line = true
where_single_line = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Pattern Matching
condense_wildcard_suffixes = true

# Miscellaneous
format_strings = true