hard_tabs = false
tab_spaces = 2

max_width = 100
use_small_heuristics = "Max"

comment_width = 100
wrap_comments = true

trailing_comma = "Never"
match_block_trailing_comma = true

fn_single_line = true
where_single_line = true

imports_granularity = "One"
